### ISSUE TITLE
ID as a string is not supporting

### ISSUE THREAD

**Issue by ecSpl01t** [AzouKr/sqlite-gui-node#8]
Hi there!
I'm just started to use your package and faced the problem related to that route `/getrecord/:tablename/:label/:id`.
Inside of that route, you're expecting `id` as a number. Could you add support `id` as a string (fetchRecord(db, tablename, label, Number(id)))?
Maybe just check it if that `id` is defined, perhaps this will be enough.

if I removed Number constructor, I needed also fix in some functions of databaseFunctions/sqlGenerator  ${label} = ${id} by wrapping {$id} -> "${id}"

Also, I cannot save data as json.

**Comment by ecSpl01t** [comment]
Please don't use everywhere `vh` units in css, because it breaks many things with a lot of data.

"Avoid overusing vh units unless you're designing something that specifically requires them, and ensure you account for potential viewport height changes, especially on mobile devices. If you're targeting flexible layouts or components that should adjust based on content, use relative units like em, rem, %, or auto to ensure better consistency and adaptability."

**Comment by AzouKr** [comment]
Hello @ecSpl01t thank you for mentioning the problem of Id, currently is being fixed and will be published these coming days.

For saving data as json you need to parse the json as string in order to save it because sql doesn't support Object type.

And for the View (HTML & CSS) thank you for your feedback, we will redo the interfaces and the design in the coming days to look good.

Again thank you for your feedbacks and stay tuned for the release in the coming days.

**Comment by AzouKr** [comment]
@ecSpl01t the string ID problem has been fixed you can run: 
```
$ npm update sqlite-gui-node
```

to get the updated package, thank you for your feedback.
